name: ner-backend
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - fastapi
  - uvicorn
  - sqlalchemy
  - sqlite
  - pip:
    - gliner
    - python-multipart
    - pydantic[email]